---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - rm -f Gemfile.lock
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 4.0" CHECK=test PARALLEL_TEST_PROCESSORS=12
  - rvm: 2.4.2
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test_with_coveralls
  - rvm: 2.4.2
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=rubocop
  - rvm: 2.4.2
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
  - rvm: 2.4.1
    bundler_args: --without development
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/centos-7
    services: docker
    sudo: required
  - rvm: 2.4.1
    bundler_args: --without development
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/debian-8
    services: docker
    sudo: required
  - rvm: 2.4.1
    bundler_args: --without development
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/ubuntu-14.04
    services: docker
    sudo: required
  - rvm: 2.4.1
    bundler_args: --without development
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04
    services: docker
    sudo: required
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "FAK3Izs5bSZyblGvcFnGWm0exZV5+v9pbwfRDD2oihWxX3U3pArGW+3XcwcJfLQgrUYBsOTmHC8yPjlgTBYeIt/5pvg9X+3jwNgeto6kozpI/nvAq4NtcHhzxRejuPELhFYeXZ3hEw0w+v/ZRo2cNLwI0LLpiWEDvCMZN1CJ2RY="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
